facebook:
  client:
    clientId: 451922685430995
    clientSecret: 2534908477cd43be8ed18e79917d93b2
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

github:
  client:
    clientId: e4b4d73cc52b8ced68fd
    clientSecret: 55c4c2f055d9128eb688af8286aba57358924c4d
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    prefer-token-info: false
    userInfoUri: https://api.github.com/user

server:
  port: 8089

spring:
  http:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB